project:
  type: website
  output-dir: docs
  
website:
  title: "Kakamana's Blogs"
  site-url: https://kakamana.github.io
  description: "This is kakamana's personal blog."
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd      
      - about.qmd 
    right:      
      - about.qmd
      - icon: github
        href: https://kakamana.github.io
      - icon: twitter
        href: https://twitter.com/Nerdy_kakamana
format:
  html:
    theme: cosmo
    css: styles.css



